---
- name: Getting facts
  hosts: wireguard
  become: yes
  user: "{{ user }}"
  gather_facts: true

- hosts: wireguard
  become: yes
  user: "{{ user }}"
  roles:
  - server_install

- hosts: wireguard
  become: yes
  user: "{{ user }}"
  roles:
  - configure_server
